### ISSUE TITLE
BMA423 Datsheet Link is Broken

### ISSUE THREAD

**Issue by rastagraffix** [sqfmi/watchy-docs#27]
A search of the Bosch site doesn't turn up any product data, but I was able to track down this link which still works:
]
  https://ae-bst.resource.bosch.com/media/_tech/media/datasheets/BST-BMA423-DS000.pdf

I've stashed away a copy of the PDF as well, in case the above link vanishes, too.

**Comment by sqfmi** [comment]
Thanks! Fixed
