### ISSUE TITLE
Getting started documentation states "there is a bug in 2.0.3" in regards to esp32 without any context

### ISSUE THREAD

**Issue by synthead** [sqfmi/watchy-docs#35]
On this line in the documentation...

https://github.com/sqfmi/watchy-docs/blob/7745a5c5468eae52368b099e398370f7bce94fde/docs/getting-started.md?plain=1#L69

...it reads:

> Note: there is a bug in 2.0.3, please use 2.0.2 until it is fixed

This is not very descriptive.  What bug?  How do we know if it's fixed?  How do we know if we're encountering the bug?  It'd be great to link to an issue with this text :+1:

**Comment by sqfmi** [comment]
Fixed in latest release
