### ISSUE TITLE
Add a link to the wiki to make screenshots

### ISSUE THREAD

**Issue by Cqoicebordel** [sqfmi/watchy-docs#68]
On https://watchy.sqfmi.com/docs/create-watchface/, there are a lots of nice explanation, but none on how to make a screenshot of the Watchy.

It took me ***way too long*** to find the wiki article explaining how to : https://github.com/sqfmi/Watchy/wiki/Screenshots-of-Watchfaces

So, a link should be added to it on the official site, to make sure it's easily findable.

**Comment by vr-varad21** [comment]
i would like to work on this issue would u please assign it to me?

**Comment by sqfmi** [comment]
Thanks for the feedback! Will add it to the docs
